sudo: required

language: go
go: 1.9.x

services:
  - docker

before_install:
  - rvm install 2.4.2
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt -y install docker-ce
  - docker --version
  - docker pull wpscanteam/vulnerablewordpress
  - git clone https://github.com/wpscanteam/wpscan.git
  - cd wpscan
  - gem install bundler
  - bundle install --without test
  - sudo ln -s $(pwd)/wpscan.rb /usr/local/bin/wpscan
  - cd ..

install:
  - make setup
  - make install

script:
  - make test
  - docker ps | awk '{ print $13 }' | grep -o -P "(.*:\d+)" > vuln_targets.txt
  - docker ps -a
  - cat vuln_targets.txt
  - ./mass-wpscan -i vuln_targets.txt -p "-r --batch -e vt,tt,u,vp" -o output.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
